config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get 'login' => "auth#login"
  root "home#index"

  namespace :user do 
    get 'dashboard' => 'dashboard#index'
    get 'profile_edit' => 'profile#edit'
    patch 'profile_update' => 'profile#update_account'
    resources :companies, path: :company do 
      member do 
        get :edit_address_info
        patch :update_address_info
        get :edit_social_info
        patch :update_social_info
      end
    end
    resources :job_posts do 
      member do 
        patch :publish_job_post
      end
    end
    resources :contacts do 
      member do 
        post :send_email_to_contactee
      end
    end
  end

  resources :companies
  resources :job_posts, path: :jobposts
  resources :contacts

end

app/views/partials/_contact_form.html.erb
<div class="card rounded-0 mt-5 mb-5">
  <div class="card-body">
    <h4 class="text-muted font-weight-bold mb-5">Contact with <span class="text-site"><%= company.name %></span></h4>
    <%= form_for :contact, url: :contacts, method: :post do |f| %>
      <%= f.hidden_field :company_id, value: company.id %>
      <div class="form-group row">
        <div class="col-md-6">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control rounded-0' %>
        </div>
        <div class="col-md-6">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control rounded-0' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-6">
          <%= f.label :contact_number %>
          <%= f.text_field :contact_number, class: 'form-control rounded-0' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Your Message' %>
        <%= f.text_area :message, class: 'form-control rounded-0', rows: '6' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Submit Contact Info', class: 'btn btn-lg-custom btn-block rounded-0 btn-custom btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_error.html.erb
<div id="error_explanation">
  <% if object.errors.present? %>
    <h4 class="text-muted font-weight-bold"><%= object.errors.count %> erorrs prohibated this company from being saved</h4>
    <ul>  
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end%>
</div>

app/views/partials/_flash.html.erb
<div id="flash" class='text-center'>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %>">
      <% unless value == true  %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-primary bg-custom">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav w-100">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Latest Job Posts', job_posts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Companies', companies_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete, data: {confirm: "Are you sure you want to sign out?"}, class: "nav-link" do %>
            <i class="fas fa-sign-out-alt"></i> Sign Out
          <% end %>
        <% else %>
          <%= link_to "Login", login_path, class: "nav-link" %>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Account
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to user_dashboard_path, class: "dropdown-item" do %>
              <i class="fas fa-tachometer-alt"></i> Dashboard
            <% end %>
            <%= link_to 'javascript:void(0)', class: "dropdown-item" do %>
              <i class="fas fa-cog"></i> Settings
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <i class="fas fa-sign-out-alt"></i> Sign Out
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>