config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get 'login' => "auth#login"
  root "home#index"

  namespace :user do 
    get 'dashboard' => 'dashboard#index'
    get 'profile_edit' => 'profile#edit'
    patch 'profile_update' => 'profile#update_account'
    resources :companies, path: :company do 
      member do 
        get :edit_address_info
        patch :update_address_info
        get :edit_social_info
        patch :update_social_info
      end
    end
    resources :job_posts do 
      member do 
        patch :publish_job_post
      end
    end
    resources :contacts do 
      member do 
        post :send_email_to_contactee
      end
    end
  end

  resources :companies
  resources :job_posts, path: :jobposts
  resources :contacts

end

app/models/job_post.rb
class JobPost < ApplicationRecord

  STATUS = ['pending', 'published', 'active', 'inactive']
  JOB_TYPE = ['Part Time', 'Full Time', 'Remote Work', 'Contract']
  EXPERIENCE_REQUIRED = ['6 Months - 1 Year', '1 Year - 2 Year', '2 Year - 3 Year', '3 Year - 5 Year', '5 Year - 8 Year', '8+ Year']

  include Companyable
  paginates_per 10
  has_many :job_post_keywords
  has_many :keywords, through: :job_post_keywords
  validates :job_title, :job_description, :required_experience, presence: true

  before_create :set_default_status

  acts_as_taggable_on :job_keywords

  def set_default_status
    self.status = 'pending'
  end

  def fresher_allowed?
    self.fresher_allowed == true
  end

end

# == Schema Information
#
# Table name: job_posts
#
#  id                      :integer          not null, primary key
#  cover_image             :string
#  eligibility_criteria    :string
#  fresher_allowed         :boolean
#  job_description         :text
#  job_post_keywords_count :integer
#  job_title               :string
#  job_type                :string
#  published_at            :date
#  required_experience     :string
#  status                  :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  company_id              :integer
#
# Indexes
#
#  index_job_posts_on_company_id  (company_id)
#

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable

  has_one :company

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def name
    "#{self.first_name} #{self.last_name}".titleize
  end

end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  city                   :string
#  contact                :string
#  country                :string
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  nationality            :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController

  def index
    @job_posts = JobPost.order(created_at: :desc).page params[:page]
  end

  def show
    @job_post = JobPost.find(params[:id])
  end

end

app/controllers/user/companies_controller.rb
class User::CompaniesController < ApplicationController
  before_action :set_company, except: [:new, :create]
  before_action :authenticate_user!

  def new
    @company = Company.new
  end

  def edit; end

  def show; end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to user_dashboard_path, flash: { success: 'Company has been created successfully' }
    else
      render :new
    end
  end

  def edit_address_info;end

  def edit_social_info;end

  def update
    if @company.update(company_params)
      redirect_to user_company_path(@company), flash: { success: 'Company has been created successfully' }
    else
      render :edit
    end
  end  

  def destroy
    @company.destroy
    redirect_to user_dashboard_path, flash: { success: 'Company has been destroyed successfully.' }
  end

  def update_address_info
    if @company.update(address_params)
      redirect_to user_dashboard_path, flash: { success: 'Company Address has been updated successfully.' }
    end
  end

  def update_social_info
    if @company.update(social_params)
      redirect_to user_dashboard_path, flash: { success: 'Company Social Links has been updated successfully.' }
    end
  end

  private
    
    def company_params
      params.require(:company).permit!
    end

    def address_params
      params.require(:company).permit(:address, :city, :state, :country, :latitude, :longitude)
    end

    def social_params
      params.require(:company).permit(:facebook_url, :youtube_url, :google_plus_url, :twitter_url, :linkedin_url)
    end

    def set_company
      @company = Company.find(params[:id])
    end

end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_contact, except: [:index]

  def index
    @company = current_user.company
    @contacts = current_user.company.contacts
  end

  def show;end

  def send_email_to_contactee
    @email_content = @contact.email_contents.create(email_params)
    ContactNotificationMailer.response_to_contactee(@email_content).deliver_now
    redirect_to user_contact_path(@contact), flash: { success: 'Email has been sent successfully' }
  end

  private

    def email_params
      params.require(:email_content).permit!
    end

    def set_contact
      @contact = Contact.find(params[:id])
    end
    
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @company  = current_user.company if current_user.company.present? 
    @job_posts = @company.job_posts.order(created_at: :desc).limit(10) if @company.present?
  end

end

app/controllers/user/job_posts_controller.rb
class User::JobPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job_post, only: [:show, :edit, :publish_job_post, :update]
  before_action :current_company

  def index
    @job_posts = @company.job_posts.order(created_at: :desc).page params[:page]
  end

  def new
    @job_post = JobPost.new
  end

  def edit;end
  def show;end

  def create
    @job_post = @company.job_posts.create(job_post_params)
    if @job_post.save
      redirect_to user_dashboard_path, flash: { success: 'Job post has been created successfully' }
    else
      render :new
    end
  end

  def update
    if @job_post.update(job_post_params)
      redirect_to user_job_post_path(@job_post), flash: { success: 'Job post has been updated successfully' }
    else
      render :edit 
    end
  end

  def publish_job_post
    @job_post.update(status: 'published')
    redirect_to user_job_post_path(@job_post), flash: { success: 'Job post has been set to published successfully' }
  end

  private

    def job_post_params
      params.require(:job_post).permit!
    end

    def current_company
      @company = current_user.company
    end

    def set_job_post
      @job_post = JobPost.find(params[:id])
    end

end

app/controllers/user/profile_controller.rb
class User::ProfileController < ApplicationController

  def edit
    @user = current_user
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # layout 'auth'
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :contact, :city, :country, :nationality])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    user_dashboard_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'auth'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/job_posts/_form.html.erb
<%= form_for([:user, @job_post]) do |f| %>
  <%= render "partials/error", object: @job_post %>

  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.text_field :job_title, class: "form-control rounded-0" %>
  </div>

  <div class="form-group">
    <%= f.label :job_description %>
    <%= f.text_area :job_description, rows: "6", class: "form-control rounded-0" %>
  </div>

  <div class="form-group row">
    <div class="col-md-6">
      <%= f.label :job_type %>
      <%= f.select :job_type, options_for_select(JobPost::JOB_TYPE, selected: @job_post.job_type), {prompt: 'Select Job Type'}, {class: "form-control rounded-0"} %>
    </div>
    <div class="col-md-6">
      <%= f.label :required_experience %>
      <%= f.select :required_experience, options_for_select(JobPost::EXPERIENCE_REQUIRED, selected: @job_post.required_experience), {prompt: 'Select Required Experience'}, {class: "form-control rounded-0"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.check_box :fresher_allowed %>
    <%= f.label :fresher_allowed %>
  </div>

  <div class="form-group">
    <%= f.label :cover_image %><br>
    <%= f.file_field :cover_image %>
  </div>

  <div class="form-group">
    <%= f.label 'Keywords(Provide some comma separated keyword for your post)' %>
    <%= f.text_field :job_keyword_list, class: "form-control rounded-0", placeholder: "Comma separated keywords", id: "job_post_keyword_list", value: @job_post.job_keyword_list.join(", ") %>
  </div>

  <div class="form-group mt-5">
    <%= f.submit class: "btn btn-success rounded-0 btn-lg" %>
    <%= link_to "Cancel", user_dashboard_path, class: "btn btn-success rounded-0 btn-lg" %>
  </div>

<% end %>

<script type="text/javascript">
  $(function () {
    $('#job_post_keyword_list').selectize({
      plugins: ['remove_button'],
      delimiter: ',',
      persist: false,
      create: function(input) {
        return {
          value: input,
          text: input
        }
      }
    });
  });
</script>

app/views/user/job_posts/_warning_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-0">
      <div class="modal-header text-center warning-modal-header">
        <h5 class="modal-title">Warning</h5>
        <button type="button" class="close close-custom" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <%= image_tag 'warning.png', style: 'width:100px;', class: 'mb-3' %>
        <p class="lead text-muted">This job post has not been published yet. It is in <span class="badge badge-danger"><%= job_post.status.capitalize %></span> state. Any job posting with <span class="badge badge-danger">Pending</span> or <span class="badge badge-danger">Inactive</span> status will not be displayed to outside users. Do you want to publish this job post now? </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary rounded-0" data-dismiss="modal">Not Now</button>
        <%= link_to "Publish Now", publish_job_post_user_job_post_path(job_post), method: :patch, class: 'btn btn-primary brn-custom rounded-0' %>
      </div>
    </div>
  </div>
</div>

app/views/user/job_posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-10">
      <h3 class="font-weight-bold text-muted mt-5">Edit job post </h3>
      <div class="card rounded-0 shadow mt-3">
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/job_posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-5 mb-5">
      <div class="card rounded-0 border-left-site">
        <div class="card-body">
          <h3 class="font-weight-bold text-muted">Listing Job Posts</h3>
        </div>
      </div>
      <div class="mt-4">
        <% @job_posts.each do |job_post| %>
          <div class="card rounded-0 mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag 'werehiring.png', class: 'img-fluid jp-img' %>
                </div>
                <div class="col-md-9">
                  <h4 class="text-muted"><%= job_post.job_title %><small class="badge badge-success ml-2 b-appended"><%= job_post.status.titleize %></small></h4>
                  <p class="font-14"><%= truncate(job_post.job_description, length: 200) %> <%= link_to "Read Full Job Description", user_job_post_path(job_post) %> </p>
                  <p class="font-14 font-weight-bold text-site">
                    <% job_post.job_keywords.each do |keyword| %>
                      #<%= keyword %>
                    <% end %>    
                  </p>
                  <%= link_to edit_user_job_post_path(job_post), class: 'btn btn-secondary btn-sm rounded-0' do %>
                    <i class="fas fa-pencil-alt mr-1"></i> Edit
                  <% end %>
                  <%= link_to user_job_post_path(job_post), class: 'btn btn-primary btn-sm rounded-0' do %>
                    <i class="fas fa-eye mr-1"></i> View
                  <% end %>
                  <%= link_to user_job_post_path(job_post), class: 'btn btn-danger btn-sm rounded-0', data: { confirm: 'Are you sure?', method: :delete } do %>
                    <i class="fas fa-trash mr-1"></i> Delete
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @job_posts %>
      </div>
    </div>
  </div>
</div>

app/views/user/job_posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-10">
      <h3 class="font-weight-bold text-muted mt-5">Create new job post for <span class="text-primary"><%= @company.name %></span> Here</h3>
      <div class="card rounded-0 shadow mt-3">
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/job_posts/show.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-md-10">
      <div class="card rounded-0">
        <div class="card-body">
          <h4 class="text-muted"><%= @job_post.job_title %> <small class="badge badge-success font-14 ml-3"><%= @job_post.job_type %></small></h4>
          <hr>
          <p class="mt-4 mb-3">
            <span class="font-weight-bold">Job Description: </span><br>
            <span class="font-13"><%= @job_post.job_description %></span>    
          </p>
          <p class="mt-4 mb-3">
            <span class="font-weight-bold">Search Keywords: </span><br>
            <% @job_post.job_keywords.each do |keyword| %>
              <span class="text-primary font-weight-bold font-14">#<%= keyword%></span>
            <% end %>
          </p>
          <p class="mt-4 mb-3">
            <span class="font-weight-bold">Experience Required: </span><br>
            <span class="font-weight-bold text-muted font-14"> <%= @job_post.required_experience %></span><br>
            <% if @job_post.fresher_allowed? %>
              <span class="font-weight-bold text-muted font-14">Note: Freshers can also apply for this position.</span>
            <% end %>
          </p>
          <% if @job_post.status == 'pending' %>
            <div class="alert alert-danger rounded-0 shadow mb-4" role="alert">
              <h4 class="alert-heading"><%= image_tag 'warning.png', width: '30' %> Warning!</h4>
              <p>The job post is in <span class="badge badge-danger">Pending</span> state. Only published job post will be displayed to outside users.</p>
              <hr>
              <p class="mb-0"><%= link_to "Click here to publish this job post", publish_job_post_user_job_post_path(@job_post), method: :patch, class: 'btn btn-primary brn-custom rounded-0' %></p>
            </div>
          <% else %>
            <p class="mt-4 mb-3">
              <span class="font-weight-bold">Status: <span class="badge badge-success"><%= @job_post.status.capitalize %></span></span>
            </p>
          <% end %>
          <%= link_to "Edit Job Post", edit_user_job_post_path(@job_post), class: "btn btn-secondary rounded-0" %>
          <%= link_to "Back", user_dashboard_path, class: "btn btn-outline-primary rounded-0" %>
        </div>
      </div>
    </div>
  </div>
</div>

<%#= render "user/job_posts/warning_modal", job_post: @job_post %>

<!-- <script>
  $(function(){
    <%# if @job_post.status == 'pending' %>
      // $(window).on('load',function(){
      //   $('#exampleModal').modal('show');
      // });
    <%# end %>
  });
</script> -->