config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get 'login' => "auth#login"
  root "home#index"

  namespace :user do 
    get 'dashboard' => 'dashboard#index'
    get 'profile_edit' => 'profile#edit'
    patch 'profile_update' => 'profile#update_account'
    resources :companies, path: :company do 
      member do 
        get :edit_address_info
        patch :update_address_info
        get :edit_social_info
        patch :update_social_info
      end
    end
    resources :job_posts do 
      member do 
        patch :publish_job_post
      end
    end
    resources :contacts do 
      member do 
        post :send_email_to_contactee
      end
    end
  end

  resources :companies
  resources :job_posts, path: :jobposts
  resources :contacts

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable

  has_one :company

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def name
    "#{self.first_name} #{self.last_name}".titleize
  end

end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  city                   :string
#  contact                :string
#  country                :string
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  nationality            :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/user/companies_controller.rb
class User::CompaniesController < ApplicationController
  before_action :set_company, except: [:new, :create]
  before_action :authenticate_user!

  def new
    @company = Company.new
  end

  def edit; end

  def show; end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to user_dashboard_path, flash: { success: 'Company has been created successfully' }
    else
      render :new
    end
  end

  def edit_address_info;end

  def edit_social_info;end

  def update
    if @company.update(company_params)
      redirect_to user_company_path(@company), flash: { success: 'Company has been created successfully' }
    else
      render :edit
    end
  end  

  def destroy
    @company.destroy
    redirect_to user_dashboard_path, flash: { success: 'Company has been destroyed successfully.' }
  end

  def update_address_info
    if @company.update(address_params)
      redirect_to user_dashboard_path, flash: { success: 'Company Address has been updated successfully.' }
    end
  end

  def update_social_info
    if @company.update(social_params)
      redirect_to user_dashboard_path, flash: { success: 'Company Social Links has been updated successfully.' }
    end
  end

  private
    
    def company_params
      params.require(:company).permit!
    end

    def address_params
      params.require(:company).permit(:address, :city, :state, :country, :latitude, :longitude)
    end

    def social_params
      params.require(:company).permit(:facebook_url, :youtube_url, :google_plus_url, :twitter_url, :linkedin_url)
    end

    def set_company
      @company = Company.find(params[:id])
    end

end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_contact, except: [:index]

  def index
    @company = current_user.company
    @contacts = current_user.company.contacts
  end

  def show;end

  def send_email_to_contactee
    @email_content = @contact.email_contents.create(email_params)
    ContactNotificationMailer.response_to_contactee(@email_content).deliver_now
    redirect_to user_contact_path(@contact), flash: { success: 'Email has been sent successfully' }
  end

  private

    def email_params
      params.require(:email_content).permit!
    end

    def set_contact
      @contact = Contact.find(params[:id])
    end
    
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @company  = current_user.company if current_user.company.present? 
    @job_posts = @company.job_posts.order(created_at: :desc).limit(10) if @company.present?
  end

end

app/controllers/user/job_posts_controller.rb
class User::JobPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job_post, only: [:show, :edit, :publish_job_post, :update]
  before_action :current_company

  def index
    @job_posts = @company.job_posts.order(created_at: :desc).page params[:page]
  end

  def new
    @job_post = JobPost.new
  end

  def edit;end
  def show;end

  def create
    @job_post = @company.job_posts.create(job_post_params)
    if @job_post.save
      redirect_to user_dashboard_path, flash: { success: 'Job post has been created successfully' }
    else
      render :new
    end
  end

  def update
    if @job_post.update(job_post_params)
      redirect_to user_job_post_path(@job_post), flash: { success: 'Job post has been updated successfully' }
    else
      render :edit 
    end
  end

  def publish_job_post
    @job_post.update(status: 'published')
    redirect_to user_job_post_path(@job_post), flash: { success: 'Job post has been set to published successfully' }
  end

  private

    def job_post_params
      params.require(:job_post).permit!
    end

    def current_company
      @company = current_user.company
    end

    def set_job_post
      @job_post = JobPost.find(params[:id])
    end

end

app/controllers/user/profile_controller.rb
class User::ProfileController < ApplicationController

  def edit
    @user = current_user
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # layout 'auth'
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :contact, :city, :country, :nationality])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    user_dashboard_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'auth'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/dashboard/_alert_notice.html.erb
<div class="alert alert-primary rounded-0 shadow mt-4" role="alert">
  <h4 class="alert-heading">Notice!</h4>
  <p>Hi <span class="font-weight-bold"><%= company.user.email %></span> your company has been submitted successfully and it is in under varification state. Since we use many sources to avoid any case of fraud so it may take upto 2-3 days to varify all the details of company provided by you. </p>
  <hr>
  <p class="mb-0">Meanwhile you can create job posting for your company but it will be listable to outside users only once your company has been approved by our administration. Thanks.</p>
</div>

app/views/user/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% unless @user.company.present? %>
        <div class="mt-5 mb-5">
          <div class="card rounded-0">
            <div class="card-body">
              <p class="lead">Hi! <span class="badge badge-success"><%= @user.email%></span> you have not created your company yet just because your profile is not completed yet. Your dashboard will display stats once you successfully create your company. Please complete your profile first.</p>
              <%= link_to "Complete your profile", user_profile_edit_path, class: "btn btn-primary btn-lg rounded-0 btn-custom" %>
              <%= link_to "Create Your Company", new_user_company_path, class: "btn btn-primary btn-lg rounded-0 btn-custom" %>
            </div>
          </div>
        </div>
      <% else %>
        <% unless @company.approved? %>
          <%= render 'user/dashboard/alert_notice', company: @company %>
        <% end %>
        <div class="row mt-5 mb-5">
          <div class="col-md-6">
            <div class="card rounded-0">
              <div class="card-body">
                <h3 class="text-muted font-weight-bold"><%= @company.name %></h3>
                <small class="badge badge-secondary"><%= @company.status.capitalize %></small>
                <p class="mb-1 mt-4">
                  <i class="fas fa-envelope"></i> 
                  <span class="ml-1"><%= @company.email %></span>
                </p>
                <p class="mb-1">
                  <i class="fas fa-globe"></i> 
                  <span class="ml-1"><%= @company.website %></span>
                </p>
                <p class="mb-1">
                  <i class="fas fa-phone"></i> 
                  <span class="ml-1">+91 <%= @company.contact_one %></span>
                </p>
                <div class="mt-4 mb-4">
                  <% if @company.address_exists? %>
                    <hr>
                    <p class="mb-1 mt-2"><span class="text-muted font-weight-bold">Address:</span> <%= @company.address || 'NA' %></p>
                    <p class="mb-1"><span class="text-muted font-weight-bold">City:</span> <%= @company.city || 'NA' %></p>
                    <p class="mb-1"><span class="text-muted font-weight-bold">State:</span> <%= @company.state || 'NA' %></p>
                    <p class="mb-3"><span class="text-muted font-weight-bold">Country:</span> <%= @company.country || 'NA' %></p>
                    <%= link_to edit_address_info_user_company_path(@company), class: "btn btn-primary btn-custom rounded-0", data: { toggle: "modal", target: "#addressModal", remote: true } do %>
                      <i class="fas fa-pencil-alt mr-2"></i> Edit Address Information
                    <% end %>
                  <% else %>
                    <%= link_to edit_address_info_user_company_path(@company), class: "btn btn-primary btn-custom rounded-0", data: { toggle: "modal", target: "#addressModal", remote: true } do %>
                      <i class="fas fa-plus mr-2"></i> Add Address Information
                    <% end %>
                  <% end %>
                </div>
                <div class="mt-4 mb-4">
                  <% if @company.social_links_exists? %>
                    <hr>
                    <p class="mb-1 mt-2">
                      <span class="text-muted font-weight-bold">
                        <i class="fab fa-facebook-square"></i> 
                      </span> 
                      <a href="<%= @company.facebook_url %>" target="_blank"><%= @company.facebook_url || 'NA' %></a>
                    </p>
                    <p class="mb-1">
                      <span class="text-muted font-weight-bold">
                        <i class="fab fa-linkedin"></i> 
                      </span> 
                      <a href="<%= @company.linkedin_url %>" target="_blank"><%= @company.linkedin_url || 'NA' %></a>
                    </p>
                    <p class="mb-1">
                      <span class="text-muted font-weight-bold">
                        <i class="fab fa-youtube-square"></i> 
                      </span> 
                      <a href="<%= @company.youtube_url %>" target="_blank"><%= @company.youtube_url || 'NA' %></a>
                    </p>
                    <p class="mb-1">
                      <span class="text-muted font-weight-bold">
                        <i class="fab fa-google-plus-square"></i> 
                      </span> 
                      <a href="<%= @company.google_plus_url %>" target="_blank"><%= @company.google_plus_url || 'NA' %></a>
                    </p>
                    <p class="mb-3">
                      <span class="text-muted font-weight-bold">
                        <i class="fab fa-twitter-square"></i> 
                      </span> 
                      <a href="<%= @company.twitter_url %>" target="_blank"><%= @company.twitter_url || 'NA' %></a>
                    </p>
                    <%= link_to edit_social_info_user_company_path(@company), class: "btn btn-primary btn-custom rounded-0", data: { toggle: "modal", target: "#socialInfoModal", remote: true } do %>
                      <i class="fas fa-pencil-alt mr-2"></i> Edit Social Links
                    <% end %>
                  <% else %>
                    <%= link_to edit_social_info_user_company_path(@company), class: "btn btn-primary btn-custom rounded-0", data: { toggle: "modal", target: "#socialInfoModal", remote: true } do %>
                      <i class="fas fa-plus mr-2"></i> Add Social Links
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card rounded-0">
              <div class="card-body">
                <% if @job_posts.present? %>
                  <h5 class="text-muted font-weight-bold">Listing company's job post</h5>
                  <div class="list-group">
                    <% @job_posts.each do |job_post| %>
                      <%= link_to job_post.job_title, user_job_post_path(job_post), class: 'list-group-item list-group-item-action' %>
                    <% end %>
                  </div>
                  <%= link_to new_user_job_post_path, class: "btn btn-primary rounded-0 btn-custom mt-3" do %>
                    <i class="fas fa-plus mr-2"></i> New Job Post
                  <% end %>
                  <%= link_to user_job_posts_path, class: "btn btn-primary rounded-0 btn-custom mt-3" do %>
                    <i class="fas fa-list mr-2"></i> View All Job Posts
                  <% end %>
                <% else %>
                  <p class="lead text-muted">Your company haven't created any job post yet. Please create first job post for your company. </p>
                  <%= link_to new_user_job_post_path, class: "btn btn-primary rounded-0 btn-custom" do %>
                    <i class="fas fa-plus mr-2"></i> New Job Post
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="row mt-5">
              <div class="col-md-6">
                <div class="card rounded-0">
                  <div class="card-body text-center">
                    <h5 class="text-muted font-weight-bold">Total<br> Jobs Posted</h5>
                    <h1 class="mt-4 text-site font-70 font-weight-bold"><%= @company.job_posts_count || 0 %></h1>
                    <%= link_to "View All Job Posts", user_job_posts_path, class: 'btn btn-light-site' %>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="card rounded-0">
                  <div class="card-body text-center">
                    <h5 class="text-muted font-weight-bold">Total<br> Enquries Received</h5>
                    <h1 class="mt-4 text-site font-70 font-weight-bold"><%= @company.contacts_count || 0 %></h1>
                    <%= link_to "View Contact Enquries", user_contacts_path, class: 'btn btn-light-site' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end%>
    </div>
  </div>
</div>

<div class="modal fade" id="addressModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>

<div class="modal fade" id="socialInfoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>