config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  get 'login' => "auth#login"
  root "home#index"

  namespace :user do 
    get 'dashboard' => 'dashboard#index'
    get 'profile_edit' => 'profile#edit'
    patch 'profile_update' => 'profile#update_account'
    resources :companies, path: :company do 
      member do 
        get :edit_address_info
        patch :update_address_info
        get :edit_social_info
        patch :update_social_info
      end
    end
    resources :job_posts do 
      member do 
        patch :publish_job_post
      end
    end
    resources :contacts do 
      member do 
        post :send_email_to_contactee
      end
    end
  end

  resources :companies
  resources :job_posts, path: :jobposts
  resources :contacts

end

app/models/job_post.rb
class JobPost < ApplicationRecord

  STATUS = ['pending', 'published', 'active', 'inactive']
  JOB_TYPE = ['Part Time', 'Full Time', 'Remote Work', 'Contract']
  EXPERIENCE_REQUIRED = ['6 Months - 1 Year', '1 Year - 2 Year', '2 Year - 3 Year', '3 Year - 5 Year', '5 Year - 8 Year', '8+ Year']

  include Companyable
  paginates_per 10
  has_many :job_post_keywords
  has_many :keywords, through: :job_post_keywords
  validates :job_title, :job_description, :required_experience, presence: true

  before_create :set_default_status

  acts_as_taggable_on :job_keywords

  def set_default_status
    self.status = 'pending'
  end

  def fresher_allowed?
    self.fresher_allowed == true
  end

end

# == Schema Information
#
# Table name: job_posts
#
#  id                      :integer          not null, primary key
#  cover_image             :string
#  eligibility_criteria    :string
#  fresher_allowed         :boolean
#  job_description         :text
#  job_post_keywords_count :integer
#  job_title               :string
#  job_type                :string
#  published_at            :date
#  required_experience     :string
#  status                  :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  company_id              :integer
#
# Indexes
#
#  index_job_posts_on_company_id  (company_id)
#

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController

  def index
    @job_posts = JobPost.order(created_at: :desc).page params[:page]
  end

  def show
    @job_post = JobPost.find(params[:id])
  end

end

app/controllers/user/job_posts_controller.rb
class User::JobPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job_post, only: [:show, :edit, :publish_job_post, :update]
  before_action :current_company

  def index
    @job_posts = @company.job_posts.order(created_at: :desc).page params[:page]
  end

  def new
    @job_post = JobPost.new
  end

  def edit;end
  def show;end

  def create
    @job_post = @company.job_posts.create(job_post_params)
    if @job_post.save
      redirect_to user_dashboard_path, flash: { success: 'Job post has been created successfully' }
    else
      render :new
    end
  end

  def update
    if @job_post.update(job_post_params)
      redirect_to user_job_post_path(@job_post), flash: { success: 'Job post has been updated successfully' }
    else
      render :edit 
    end
  end

  def publish_job_post
    @job_post.update(status: 'published')
    redirect_to user_job_post_path(@job_post), flash: { success: 'Job post has been set to published successfully' }
  end

  private

    def job_post_params
      params.require(:job_post).permit!
    end

    def current_company
      @company = current_user.company
    end

    def set_job_post
      @job_post = JobPost.find(params[:id])
    end

end

app/views/job_posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-5 mb-5">
      <div class="card rounded-0 border-left-site">
        <div class="card-body">
          <h3 class="font-weight-bold text-muted">Listing Job Posts</h3>
        </div>
      </div>
      <div class="mt-4">
        <% @job_posts.each do |job_post| %>
          <div class="card rounded-0 mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag 'werehiring.png', class: 'img-fluid jp-img' %>
                </div>
                <div class="col-md-9">
                  <h4 class="text-muted"><%= job_post.job_title %><small class="badge badge-success ml-2 b-appended"><%= job_post.status.titleize %></small></h4>
                  <h6 class="text-muted font-14 font-weight-bold">@ <span class="text-site"><%= link_to job_post.company.name, company_path(job_post.company) %></span></h6>
                  <p class="font-14"><%= truncate(job_post.job_description, length: 200) %> <%= link_to "Read Full Job Description", user_job_post_path(job_post) %> </p>
                  <p class="font-14 font-weight-bold text-site">
                    <% job_post.job_keywords.each do |keyword| %>
                      #<%= keyword %>
                    <% end %>    
                  </p>
                  <%= link_to job_post, class: 'btn btn-primary btn-sm rounded-0' do %>
                    <i class="fas fa-eye mr-1"></i> View
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @job_posts %>
      </div>
    </div>
  </div>
</div>

app/views/job_posts/show.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-md-9">
      <div class="card rounded-0">
        <div class="card-body">
          <h4 class="text-muted"><%= @job_post.job_title %> <small class="badge badge-success font-14 ml-3"><%= @job_post.job_type %></small></h4>
          <hr>
          <p class="mt-4 mb-3">
            <span class="font-weight-bold">Job Description: </span><br>
            <span class="font-13"><%= @job_post.job_description %></span>    
          </p>
          <p class="mt-4 mb-3">
            <span class="font-weight-bold">Search Keywords: </span><br>
            <% @job_post.job_keywords.each do |keyword| %>
              <span class="text-primary font-weight-bold font-14">#<%= keyword%></span>
            <% end %>
          </p>
          <p class="mt-4 mb-3">
            <span class="font-weight-bold">Experience Required: </span><br>
            <span class="font-weight-bold text-muted font-14"> <%= @job_post.required_experience %></span><br>
            <% if @job_post.fresher_allowed? %>
              <span class="font-weight-bold text-muted font-14">Note: Freshers can also apply for this position.</span>
            <% end %>
          </p>
          <% if @job_post.status == 'pending' %>
            <div class="alert alert-danger rounded-0 shadow mb-4" role="alert">
              <h4 class="alert-heading"><%= image_tag 'warning.png', width: '30' %> Warning!</h4>
              <p>The job post is in <span class="badge badge-danger">Pending</span> state. Only published job post will be displayed to outside users.</p>
              <hr>
              <p class="mb-0"><%= link_to "Click here to publish this job post", publish_job_post_user_job_post_path(@job_post), method: :patch, class: 'btn btn-primary brn-custom rounded-0' %></p>
            </div>
          <% else %>
            <p class="mt-4 mb-3">
              <span class="font-weight-bold">Status: <span class="badge badge-success"><%= @job_post.status.capitalize %></span></span>
            </p>
          <% end %>
          <%= link_to "Back", :back, class: "btn btn-outline-primary rounded-0" %>
        </div>
      </div>
      <%= render "partials/contact_form", company: @job_post.company %>
    </div>
    <div class="col-md-3">
      <div class="card rounded-0">
        <div id="map"></div>
      </div>
    </div>
  </div>
</div>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFBYM37YGMTdgkEp9fipPljSjprTDZL8Y&callback=initMap">
</script>

<script type="text/javascript">
  function initMap() {
    latitude = <%= @job_post.company.latitude %>;
    longitude = <%= @job_post.company.longitude %>;
    var venue = {lat: latitude, lng: longitude};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 16,
      center: venue
    });
    var marker = new google.maps.Marker({
      position: venue,
      map: map
    });
  }
</script>